### ISSUE TITLE
Rename KotekanProcess

### ISSUE THREAD

**Issue by jrs65** [kotekan/kotekan#275]
I'm going to make the controversial suggestion that we find and replace through the whole codebase to rename `KotekanProcess`. This is because the terminology is extremely awkward and confusing, as we are always having to qualify the difference between a KotekanProcess class and the kotekan OS process that's running.

Having chatted with @nritsche and @tristpinsm about it now, suggestions that we have (in my personal, descending order):
- `kotekanTask`
- `kotekanAction`
- `kotekanWorker`
- `kotekanUnit`
- `kotekanModule`
- `kotekanThread` (though they don't actually map 1-1 to threads so that seems like a bad idea)

@andrerenard thoughts?

**Comment by cubranic** [comment]
I’m working on renaming KotekanProcess to Stage. The rename was entirely mechanical and quick, but now I realize there are all these places talking about “process”. Example:

- in core/kotekan_process.hpp, there is a macro REGISTER_KOTEKAN_PROCESS, which is used by every subclass of Stage. Should I change that to REGISTER_KOTEKAN_STAGE?

- prometheusMetrics: method “add_process_metric”

- processFactory: the class name; method “kotekan_register_process”

- various comments talking about “processes”

- the name of the directory lib/process

Should I update all of those to “stage”?

**Comment by cubranic** [comment]
OK, I think I'm done for now and would like some feedback: see PR #362. There are a few things left unfinished, but I shouldn't necessarily be the one to do them.

- config file parameter is still named "kotekan_process", rather than "kotekan_stage" because I wanted changes to config files to be done by someone more familiar with their syntax and effects

- subclasses of `kotekan::Stage` (formerly `KotekanProcess`) that are not in `lib/core` need to have updated their class, method, member, and variable names, as well as comments (API and in-code) to reflect the change "process" -> "stage". I'd like this to be done by their authors (I'll handle the baseband ones), if we agree that the changes (and choices) I made are OK.

- I think @andrerenard said that stage subclasses can remain outside the "kotekan" namespace for now. I'm not sure where they should go, but probably they should be put *somewhere*.
- directory 'lib/processes' needs to be renamed to 'lib/stages'. I can do this,  but wanted to do it last.

**Important:** Where I renamed classes, I used capitalized `CamelCase`, as we've agreed. One ambiguity in our style standard was file names. I choose lowercased `snake_case`, e.g., `stage.hpp` and `stage_factory.hpp`. Opinions please?

**Comment by andrerenard** [comment]
This was done in #362
