### ISSUE TITLE
prometheusMetric timestamp issues

### ISSUE THREAD

**Issue by jrs65** [kotekan/kotekan#353]
Prometheus drops metrics where the time samples are much older (or newer) than what it thinks the current time is. This causes metrics that are updated irregularly to dissappear within time series.

I propose that we either: 
- Move to the behaviour that prometheus expects and the timestamp returned on a `/metrics` scrape is the current timestamp.
- We move to a policy where each metric is updated every cycle by the relevant process, but the counts are only increased when they change, i.e. dropped frame counts are posted to prometheusMetrics every cycle, but the counter is only incremented when a frame is dropped.

The former seems like a better option to me.

**Comment by cubranic** [comment]
I *think* we don't care about timestamps anywhere, in which case there is no reason *not* to go with option 1.

If we do care about the timestamps, a variation for the second option is to distinguish between "counter" and "gauge" type metrics. (Prometheus terminology). 

Counters can only by increased (this should be controlled by an API), but don't need to be refreshed by the stages every cycle, since they remain "current" between updates. For them, we always return the "now" timestamp on Prometheus scrape. (Or, more simply, don't include a timestamp and Prometheus server doing the scrape fills it in.)

Gauges are explicitly _set_ to a value that is current at that time, so for them we do keep the timestamp of the last update and return it on Prometheus scrape.

**Comment by jrs65** [comment]
@cubranic @andrerenard do you think this would be a lot of work to fix? Could be a good hot fix candidate actually, as it messes up some of the metric analysis I want to do for dropped frames.

**Comment by jrs65** [comment]
Also, I guess there are a few things that we output which probably are gauges. As Davor says we might want to distinguish between them. To some degree that's what's causing the problem I'm seeing in the first place as my "counters" are getting updated fairly infrequently, and we're using a "gauge" like behaviour.

**Comment by cubranic** [comment]
@jrs65 I started on this -- have a look in branch [_prometheus-metrics-gauge-counter_](https://github.com/kotekan/kotekan/tree/prometheus-metrics-gauge-counter), in particular the latest commit, 475b0ec6b6640fd1e9ac3bc783d1c94b8acd7b74. It gives you the API similar to other Prometheus client libraries, where you create the metric in a constructor or at the beginning of your Stage's main loop:
```c++
request_count_metric(
	        prometheusMetrics::instance()
	        .add_stage_counter("kotekan_baseband_requests_total", "baseband")
	        )
```
and then increment it when necessary with: `request_count_metric.inc()`.

It's not done yet because there is a number of places that still use gauge-style metrics which I'm quite sure should be counters, because they use dynamically constructed labels. E.g., in visAccumulate.cpp:
```c++
                        std::string labels = fmt::format("freq_id=\"{}\"", frame.freq_id);
                        prometheusMetrics::instance().add_stage_metric(
                            "kotekan_visaccumulate_skipped_frame_total", unique_name,
                            skipped_frame_total, labels);
```
What I'd like is something like this:
```c++
// in constructor:
skipped_frame_counter = prometheusMetrics::instance()
  .add_stage_counter("kotekan_visaccumulate_skipped_frame_total", unique_name)
  .label_names({"freq_id"});

// in the loop:
skipped_frame_counter.labels({frame.freq_id}).inc();
```
I'll work on that next week before submitting a PR.

**Comment by jrs65** [comment]
The proposal API looks good. If you want to be flash, you could implement the increment as
`skipped_frame_counter.labels({frame.freq_id})++`

**Comment by jrs65** [comment]
I guess it might be difficult to automatically do the conversion from the arbitrary label type (`uint32_t` in your example) to a string.

**Comment by cubranic** [comment]
OK, that was quite massive, but I think I have it everywhere: 2f34e1ed5dc5a5b389b6006be6a4fc480db6fc5c

If someone can have a look at #436 and give me feedback on what else needs to change.
There are a few loose ends: I haven't added the doc comments yet (I plan to reuse the ones from `add_stage_metric`), the new methods use different method names (`AddCounter`/`AddGauge` instead of `add_stage_metric` and `Serialize` instead of `serialize`), but that is just to make them easier to see. I'm happy to change to the old names as the final step.

This is what it looks like:
```
// in constructor:
skipped_frame_counter = prometheusMetrics::instance()
  .AddCounter("kotekan_visaccumulate_skipped_frame_total",
       unique_name, {"freq_id"});

// in the loop:
skipped_frame_counter.Labels({std::to_string(frame.freq_id)}).inc();
```

(C++ is not smart enough to convert the int to string in an initializer_list, for constructing `vector<string>`. :-()

**Comment by andrerenard** [comment]
Thanks Davor, I will have a look.  Just to be consistent with our style guide I would request we make the function names be `snake_case` with no capitals.  However I think `add_counter`, `add_gauge` are sufficient, we likely don't need to include the word `stage` in them.

**Comment by cubranic** [comment]
Definitely. “AddStage”, etc. is just for visibility while I was refactoring this.

**Comment by andrerenard** [comment]
I kind of wish we used C++17 right now, then I think you could use `std::variant` or `std::any` to get around that `std::to_string` issue.   One solution might be to create an object which basically implements that for `int64` and `string` by accepting either in the constructor and returning whichever type it was provided.  Although that might still require you cast the int to `int64_t` or something like that to avoid compiler warnings.
