### ISSUE TITLE
visWriter: Close old acqs should be called every cycle

### ISSUE THREAD

**Issue by jrs65** [kotekan/kotekan#364]

**Comment by nritsche** [comment]
`close_old_acqs()` is called every cycle. Do we know what's wrong there?

**Comment by jrs65** [comment]
You are right. I guess I had miscounted the number of braces at the end!

In which case this is even more mysterious. Empirically acquisitions don't seem to be being closed when visWriter stops getting data for them.

**Comment by tristpinsm** [comment]
I think this is happening because of the `BufferSwitch` process disabling the input buffer. Then `visWriter` just waits at the top of the loop for a filled frame and never reaches the `close_old_acqs()` call.

This has been inconvenient for testing the pulsar gating, but I've found that I can make it release a file by enabling gating with a bogus pulsar spec and letting through a few frames (as long as enough time has passed for `visWriter` to timeout on that acq). Unfortunately this leaves short useless acquisitions laying around...

**Comment by jrs65** [comment]
Came here to say exactly what @tristpinsm said. I think I can fix this by waiting with a timeout to ensure that even with no incoming data we keep looping and closing up old acquisitions.
