### ISSUE TITLE
About half the nodes are rejecting gating config update

### ISSUE THREAD

**Issue by tristpinsm** [kotekan/kotekan#369]
Whenever I send a config update for the pulsar gating through `KotekanMaster` about half the nodes (~100) respond with 
```
{'UnknownError': 'Response={u\\'message\\': u\"configUpdater: Update to endpoint \\'/updatable_config/gating/psr0_config\\' contained value \\'dm\\' of type float (expected type number).\", u\\'code\\': 400}, Error:HTTP 400: BAD_REQUEST\\n'}
```
 The other nodes are fine and seem to be producing the gated stream as expected.

Here a typical JSON update :
```
curl csBfs:54323/update-pulsar-gating -X POST -H "Content-Type: application/json" -d '{"coeff": [[8.451188749386428e-10, -0.00013213758449419458, -6.627836033917244e-08, -4.732131671123605e-10, 2.331131336850821e-13, 4.552811969358192e-16, -1.401626224241363e-19, -3.6089049190384454e-22, -5.078171175765845e-25, 4.410000424496888e-27, 1.0968063735702019e-29, -4.2400626494554845e-32], [1.4344346305358498e-10, -0.0002592509101170875, -2.711651590138689e-07, 8.52119140931717e-11, 5.599454690706729e-13, -8.343620189603956e-17, -3.6209919173919025e-19, 1.5344960473424132e-22, 3.130489472711657e-25, -3.232114419701468e-27, -2.675647370327176e-30, 3.085769738832778e-32], [4.074491285715008e-10, -0.0003465987739188493, 4.6654664661639314e-08, 5.166329675391741e-10, 5.284976788026692e-14, -4.987223509650824e-16, -4.02888773664995e-20, 5.492535530479008e-22, 3.583726999905542e-25, -1.125232102606971e-26, -6.222557697821949e-30, 1.4221809126102123e-31]], "t_ref": [58514.6041666666, 58514.8124999999, 58515.0208333333], "phase_ref": [2909514952.315827, 2909565128.0972075, 2909615303.838368], "rot_freq": 2.787546496219, "dm": 158.521, "segment": 18000.0, "pulsar_name": "B1933+16", "pulse_width": 0.0177, "enabled": true}'
```
The relevant key is `"dm": 158.521`.

It's worth noting that if I send an empty update to disable gating, then all the nodes seem to respond successfully.
```
curl csBfs:54323/update-pulsar-gating -X POST -H "Content-Type: application/json" -d '{"coeff": [[0]], "t_ref": [0], "phase_ref": [0], "rot_freq": 0, "dm": 0, "segment": 0, "enabled": false, "pulsar_name": "not_a_pulsar", "pulse_width": 0}'
```
Here, `"dm": 0`.

**Comment by andrerenard** [comment]
That error is coming from the type checking in the `configUpdater`, for some reason it seems to be expecting the number to be an integer, not a float. 

I think what's happening is this:

- When the GPU nodes restart when gating is disabled `dm: 0` they set the expected type to integer. 
- Nodes which haven't restarted (started with the default float `dm`), or started when gating was enabled set `dm` as a float.

So for nodes which are restarted when `dm: 0` we will not be able to set the `dm` until they are restarted...

We can either relax the requirement of numbers being float or integer only, or send in `dm: 0.0` to disable gating which should keep the type as float (although @nritsche might want to comment on if that will work).

**Comment by andrerenard** [comment]
Also it looks like `dm: 0` is also accepted as a float.  Which if we are being strict about floats vs. integers, maybe should not be accepted.   That would also resolve this issue.

**Comment by tristpinsm** [comment]
I see. Going forward I'll make sure to send floats every time and see if we gradually recover all the nodes.

**Comment by andrerenard** [comment]
Going forward I think we still want to update the `configUpdater` to either be more relaxed about numerical types, or enforce that floats require a float formatted number when updated.   @nritsche is this something you can look into?

**Comment by nritsche** [comment]
If I remember correctly, we had decided the `configUpdater` should be relaxed about differing number types with the exception of a `float` coming in to update a non-float number. That meant we had to format some numbers in the config like `23.` or `0.` instead of '23' and '0' to make `configUpdater` set their initial type to `float`.

This effect of the type being set to `non-float` when restarting after receiving an update of a `float` with a non-float number (which is allowed) is a bit unfortunate and I haven't foreseen it.
Am I correct, that it's `kotekan_master` applying the last config to a restarted node?
In that case: from the `configUpdater` side, we could only solve it by changing our previous decision and either make `configUpdater` completely relaxed about differing number-types, which might be problematic in other cases or `configUpdater` could be more strict and not accept `0` to update a float value.
The other solution would be to never send i.e. a value for `dm` without the `.`-suffix to make it a float, which is easy to go wrong again somewhere else.

**Comment by tristpinsm** [comment]
Having `configUpdater` be completely strict about types might be annoying sometimes, but at least it would be entirely predictable. I think relying on people to always be explicit with float literals will lead to something like this cropping up again at some point.

**Comment by jrs65** [comment]
It might be overkill, but given this problem and the way that some of the discussion was going with Kotekan Master, we might consider requiring formal schemas for the updates. Something along the lines of https://json-schema.org

**Comment by jrs65** [comment]
However, saying that we should figure out a short term fix for this problem. I would vote for that if in the initial config you have an integer literal (i.e. no decimal point) it will always be parsed as an int, and if we have a float literal (i.e. with the point) then it is always parsed as a literal. Updates that arrive that don't match (i.e. int update for a float property) will be rejected. This is super strict, but it's easy to remember, and I think there shouldn't be any corner cases.

@nritsche do you think we could get this fixed in the next few days? I think it would be a good candidate for being in the hot fix.

**Comment by andrerenard** [comment]
I agree with strict checking, we should just be careful if we apply this as a hot fix that it doesn't break any other endpoints which might currently be enjoying the relaxed type checking.

**Comment by nritsche** [comment]
#373 
Strict checking it is. This also includes signed/unsigned integers.
