### ISSUE TITLE
Timeout in remote communication causes Kotekan to exit

### ISSUE THREAD

**Issue by cubranic** [kotekan/kotekan#560]
Log message:
```
restClient: Timeout in make_request_blocking (10.1.50.11:12050//register-state). This might leave the restClient in an abnormal state. Exiting.
```

Reaching timeout in RPC doesn't seem like it should require such a drastic response. @nritsche?

**Comment by nritsche** [comment]
As the comment in the code above this log line explains, this is a timeout wrapping the restClient to catch the libevent bug #341 and actually a serious error case that leaves the restClient in an unknown state.

The bug is fixed with #578 though, so if this error message ever reappears, we would want to know. I will leave the drastic response to this timeout in place, just in case.

Please reopen if you disagree!
