### ISSUE TITLE
visWriter: Number of products mismatches when gating changes

### ISSUE THREAD

**Issue by nritsche** [kotekan/kotekan#658]
When turning on pulsar gating, visWriter exited with fatal error:
```
Dec 16 09:54:02 recv2 kotekan[3307]: /archive_writers/26mgated: Got new dataset ID=b2da1fde9f6de323caacc6caf8eef780 with new fingerprint=4fd083badb1f95f36481ae7b21de97c5. Creating new acquisition.
Dec 16 09:54:02 recv2 kotekan[3307]: /archive_writers/26mgated: Number of products in frame doesn't match state or file (4095 != 16356).
```
```
Dec 16 12:48:09 recv2 kotekan[1832]: /archive_writers/26mgated: Got new dataset ID=7c94327318bc9d28a3153357926740ec with new fingerprint=69ed8a5cd40ff07fecf1c162d32ab772. Creating new acquisition.
Dec 16 12:48:09 recv2 kotekan[1832]: /archive_writers/26mgated: Number of products in frame doesn't match state or file (4095 != 66).
```

**Comment by nritsche** [comment]
I had not finished my review of #606 when it was merged. Looking at it to understand this bug, I wonder what `acqs_mutex` is needed for in `visWriter`. @jrs65

**Comment by jrs65** [comment]
There are two apparent problems occurring in here:
- The fingerprint generated for the dataset ID is incorrect. 
- There is evidence that looking up both the product and the frequency state is returning the wrong states. 

Both of those could be explained if we were walking up the wrong branch of the tree. So that seems like a good place to look for the issue. 

I still can’t think of why only the gated datasets would be effected by this problem, so I fear that the issue is more widespread.

**Comment by jrs65** [comment]
If we want to test while not taking down the whole acquisition, one option would be to write a small C++ executable that uses the dataset manager and queries the broker for the tree and then calculates the fingerprint and the number of products and frequencies for the states that have been causing trouble. That would give us a starting point, although it may be the kind of thing where you have to run a whole bunch of operations at the same time to see the issue.

**Comment by jrs65** [comment]
In all this I’m kind of assuming that comet is not the problem. Other than logs not being there, I haven’t seen any evidence of this.

**Comment by nritsche** [comment]
Fixed by https://github.com/chime-experiment/comet/pull/72
