### ISSUE TITLE
Kotekan version string inconsistent

### ISSUE THREAD

**Issue by jrs65** [kotekan/kotekan#663]
For kotekan on a GPU node:
```
$ kotekan -v
Kotekan version HEAD.2019.12a.0-8000402a
```

On a recv node:
```
$ kotekan -v
Kotekan version HEAD.2019.12a.0-8000402
```
(note the lack of the trailing `a`)

**Comment by jrs65** [comment]
@andrerenard explain this one! :)

**Comment by andrerenard** [comment]
It also shouldn't be `HEAD.2019.12a.0-8000402` or `HEAD.2019.12a.0-8000402a`, it should be simply `2019.12a` in this case.   This seems to be a problem of building the code with `sudo make install` which I think is because it then doesn't have a key for accessing github.  Since if I build it without `root` it works correctly.

**Comment by jrs65** [comment]
Interesting. I use `make install` on the GPU nodes and it still doesn't get it right, even though it can access github fine.

**Comment by andrerenard** [comment]
The difference is likely down to some python difference in @shinybrar 's script.  We should either check if the FRB group has an update to `version.py` or move to `versioneer`: https://github.com/warner/python-versioneer

**Comment by andrerenard** [comment]
hmm, that is interesting.  When I do `make install` on the nodes it works as long as I log in with `ssh -A`.   There must be some strange key/user interaction going on there.   Where are you building kotekan from on the nodes?  Is it `/opt/kotekan` or your own folder?

**Comment by jrs65** [comment]
I build from `/root/richard/kotekan`, and I think it is using your ssh key to access github (at least all my changes there end up being authored by you!)

**Comment by nritsche** [comment]
I didn't review it yet, but I think @james-s-willis just swapped that script against versioneer in an open PR.

**Comment by andrerenard** [comment]
@jrs65 I think the reason it's "authored by [me]" is because of the global git settings, which get applied automatically if there isn't a local repo override.

**Comment by andrerenard** [comment]
@nritsche It looks like that change is just for the `rfi_recever.py` script.

**Comment by jrs65** [comment]
Ah okay. Then I guess it's getting my ssh-key via the agent (that is what I thought it was doing)

**Comment by nritsche** [comment]
Okay, but we that script is in the kotekan repository, so they should share the version string and script, I think.

**Comment by andrerenard** [comment]
@jrs65  Maybe when you use a key that doesn't match the global/local git repo username it fails.  I.e. It's using your key, but my username.

**Comment by jrs65** [comment]
That would make sense. Who knows what the version.py script is up to though.

I don't think having the short version string is worth a rebuild, but we could do.

**Comment by andrerenard** [comment]
@nritsche yes it does make sense they should share the same script.   Given the problems with `version.py` here, I'd be ok with trying out `versioneer` for everything, but that does change the scope of what @james-s-willis is currently working on.  If we do change we should make sure that `versionner` handles all these strange edge cases better 

@jrs65 I don't think it's worth a rebuild.  The `git-tag` seems to be what's checked and stored, so that's the important thing.

**Comment by shinybrar** [comment]
The issue is because the response from the `git-python` is different in the two runtime environments, potentially because of different python (2 vs 3) or package versions. 

The `version.py` used by Kotekan has since been improved to better deal with the edge cases, look [here](https://github.com/CHIMEFRB/frb-master/blob/master/version.py).

I support the move away from `version.py` and would suggest [dunamai](https://github.com/mtkennerly/dunamai), which is also a great project worth investigating.
