### ISSUE TITLE
Add a metric to track the last time of gain update

### ISSUE THREAD

**Issue by cubranic** [kotekan/kotekan#687]
- to ReadStage?
- with attribute for the kind of gain being updated (Cosmo/FRB/Pulsar)
- its value would be current Unix time (seconds since epoch), so it should be a counter

**Comment by andrerenard** [comment]
We need to add it at least to `ReadGain` that covers both the pulsar and FRB gain loading.  Would `0` work as the value to indicate it hasn't been able to load gains?

**Comment by cubranic** [comment]
Not the way I was thinking of using it, as time of last successful update. So if the update fails, you just don't increment it. The alert can then be by directly comparing it to the value of calibration broker's last update, or indirectly -- has it been updated in the last X time period.

Or there can be two: last update request and last successful update. If the time of the request is greater than the time of the successful update, you know the last request failed.

**Comment by andrerenard** [comment]
My concern with that would be there have been times we've manually reverted gains because the last gain solution was bad.  So I think we do need a way to distinguish the gains failed to load vs. the age of the gains.  I'm not sure the "last successful update" idea works for cases that we switch the active gains.  Also if the gains fail to load it applies default gains, which is a much larger problem than just having old gains.  So I'd vote for that being boolean flag.   Although I think it's worth having the time of last update as well, but it's tracking a slightly different error.

**Comment by cubranic** [comment]
Two metrics, one 0/1 for the success of last update, and one with the timestamp of the last update, successful or not. (Time as in the current time when the update was applied, not the time it was generated by the calibration broker.)

Label `type` to keep "frb" and "pulsar" updates separate.
