### ISSUE TITLE
Modernize CMake build files

### ISSUE THREAD

**Issue by jrs65** [kotekan/kotekan#701]
The current set of CMake files is a barely understandable, poorly structured horror show of bad practices. We should refactor these to make them logical, consistent and use modern conventions.

Suggestions for what we should do:
- [x] Build proper INTERFACE library targets, use `target_include_directories` and then `target_link_libraries` will automatically take care of including the right source files.
- [ ] Use `FindPackage` and `target_link_libraries` rather than separate source includes for dependencies.
- [x] Consistent spacing conventions.

Any more things? (edit, and add above)

This seems like the kind of task that @nritsche seems to derive unreasonable amounts of enjoyment from.

**Comment by nritsche** [comment]
More suggestions:
- [ ] Use `target_compile_features` and let cmake figure out the compiler and flags to use instead of `CMAKE_CXX_FLAGS`

**Comment by nritsche** [comment]
> Build proper INTERFACE library targets, use `target_include_directories` and then `target_link_libraries` will automatically take care of including the right source files.

An interface library does not produce build output. We currently have `kotekan_libs` as one. Otherwise, where in this project would that make sense?
In this suggestion, do you mean the interface target `kotekan_libs` should add all it's subdirectories as `target_include_directories` and then all targets that need to include anything from `kotekan_libs` should add it as `target_link_libraries`? Wouldn't that lead to a lot of unnecessary linking?
