### ISSUE TITLE
Add GPS time to the FRB L0->L1 packet

### ISSUE THREAD

**Issue by andrerenard** [kotekan/kotekan#768]
Currently the mapping from the FPGA sequence number to GPS time is done with an out-of-band communication between the L1 nodes and `fpga_master`.

To avoid this we should add the GPS time to each of the L0->L1 packets.  This has the added benefit of allowing a free running clock on the FPGAs independent of the GPS time, should we ever want that clock configuration. 

This ticket is for adding this functionality to `kotekan`, the L1 change will be tracked separately.

**Comment by cubranic** [comment]
Based on discussions with Kendrick and Dustin, and a walk-through of the L1 code, instead of GPS time, we should send `frame0` time. L1 does not use the GPS time itself, only threads frame0 time throughout the L1 pipeline until it is written into the files output on callback (msgpack), so this would be transparent to downstream consumers.
